name: video_editor
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.0
  video_trimmer: ^0.3.5
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  flutter_ffmpeg: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  
  
  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
